# Generated by Django 3.0.4 on 2020-04-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizadortipo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
                ('primeiro_dia', models.IntegerField(blank=True, null=True)),
                ('segundo_dia', models.IntegerField(blank=True, null=True)),
                ('sala_de_aula', models.IntegerField(blank=True, null=True)),
                ('percurso', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utilizadortipo',
                'managed': False,
            },
        ),
    ]
