# Generated by Django 3.0.4 on 2020-04-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_dia', models.IntegerField(blank=True, null=True)),
                ('segundo_dia', models.IntegerField(blank=True, null=True)),
                ('sala_de_aula', models.IntegerField(blank=True, null=True)),
                ('percurso', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utilizador',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Utilizadortipo',
        ),
    ]
