# Generated by Django 3.0.4 on 2020-04-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('duracao', models.IntegerField()),
                ('validada', models.IntegerField()),
                ('tipo_atividade', models.TextField(blank=True, null=True)),
                ('publico_alvo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'atividade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edicifio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_edificio', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'edicifio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ementa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(blank=True, null=True)),
                ('preco_aluno_economico', models.DecimalField(decimal_places=2, max_digits=4)),
                ('preco_aluno_normal', models.DecimalField(decimal_places=2, max_digits=4)),
                ('preco_outro_economico', models.DecimalField(decimal_places=2, max_digits=4)),
                ('preco_outro_normal', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'ementa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmentaInscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aluno_normal', models.IntegerField(blank=True, null=True)),
                ('numero_aluno_economico', models.IntegerField(blank=True, null=True)),
                ('numero_outro_normal', models.IntegerField(blank=True, null=True)),
                ('numero_outro_economico', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ementa_inscricao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('morada', models.TextField(blank=True, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto', models.IntegerField(blank=True, null=True)),
                ('localidade', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'escola',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'inscricao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localizacaoatividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('andar', models.IntegerField(blank=True, null=True)),
                ('sala', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'localizacaoatividade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipanteGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_participantes', models.IntegerField()),
                ('total_professores', models.IntegerField()),
                ('turma', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'participante_grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipanteIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorizacao', models.IntegerField()),
                ('ficheiro_autorizacao', models.CharField(max_length=255)),
                ('acompanhantes', models.IntegerField()),
            ],
            options={
                'db_table': 'participante_individual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
            ],
            options={
                'db_table': 'sessao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SessaoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('n_alunos', models.IntegerField()),
            ],
            options={
                'db_table': 'sessao_atividade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SessaoAtividadeInscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_alunos', models.IntegerField()),
            ],
            options={
                'db_table': 'sessao_atividade_inscricao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporteproprio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('hora_chegada', models.TimeField()),
                ('hora_partida', models.TimeField()),
                ('tipo_transporte', models.CharField(max_length=255)),
                ('transporte_para_campus', models.CharField(blank=True, max_length=255, null=True)),
                ('transporte_entre_campus', models.CharField(blank=True, max_length=255, null=True)),
                ('hora_entre_campus', models.TimeField()),
            ],
            options={
                'db_table': 'transporteproprio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilizadorparticipante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_estudos', models.CharField(max_length=45)),
                ('ano_estudos', models.IntegerField()),
                ('check_in', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utilizadorparticipante',
                'managed': False,
            },
        ),
    ]
