# Generated by Django 3.0.4 on 2020-03-31 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0003_auto_20200331_0440'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inscricao',
            table='inscricao',
        ),
    ]
