# Generated by Django 3.0.4 on 2020-03-31 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0004_auto_20200331_1712'),
        ('inscricao', '0004_auto_20200331_1928'),
    ]

    operations = [
    ]
