# Generated by Django 3.0.4 on 2020-04-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0005_merge_20200331_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ementa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('preco_aluno_economico', models.DecimalField(decimal_places=2, max_digits=4)),
                ('preco_aluno_normal', models.DecimalField(decimal_places=2, max_digits=4)),
                ('preco_outro_economico', models.DecimalField(decimal_places=2, max_digits=4)),
                ('preco_outro_normal', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'ementa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmentaPratoInscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aluno_normal', models.IntegerField(blank=True, null=True)),
                ('numero_aluno_economico', models.IntegerField(blank=True, null=True)),
                ('numero_outro_normal', models.IntegerField(blank=True, null=True)),
                ('numero_outro_economico', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ementa_prato_inscricao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporteproprio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('hora_chegada', models.TimeField()),
                ('hora_partida', models.TimeField()),
                ('tipo_transporte', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'transporteproprio',
                'managed': False,
            },
        ),
    ]
