# Generated by Django 3.0.4 on 2020-04-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0006_ementa_ementapratoinscricao_transporteproprio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'prato',
                'managed': False,
            },
        ),
    ]
