# Generated by Django 3.0.4 on 2020-04-02 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0008_auto_20200401_2130'),
        ('inscricao', '0005_merge_20200331_2137'),
    ]

    operations = [
    ]
