# Generated by Django 3.0.4 on 2020-04-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0009_merge_20200401_2341'),
        ('inscricao', '0009_merge_20200402_0330'),
    ]

    operations = [
    ]
