# Generated by Django 3.0.4 on 2020-04-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilizadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('morada', models.TextField(blank=True, null=True)),
                ('contacto', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'campus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidadeorganica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'unidadeorganica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password_digest', models.CharField(blank=True, max_length=255, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('numero_telemovel', models.IntegerField()),
                ('cartao_cidadao', models.IntegerField()),
                ('deficiencias', models.CharField(max_length=255)),
                ('permitir_localizacao', models.IntegerField()),
                ('utilizar_dados_pessoais', models.IntegerField()),
                ('validado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utilizador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilizadorparticipante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola', models.IntegerField()),
                ('area_estudos', models.CharField(max_length=45)),
                ('ano_estudos', models.IntegerField()),
                ('turma', models.CharField(max_length=45)),
                ('total_participantes', models.IntegerField(blank=True, db_column='total__participantes', null=True)),
                ('total_professores', models.IntegerField(blank=True, null=True)),
                ('autorizacao', models.CharField(blank=True, max_length=45, null=True)),
                ('ficheiro_autorizacao', models.CharField(blank=True, max_length=45, null=True)),
                ('numero_acompanhantes', models.IntegerField(blank=True, null=True)),
                ('check_in', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utilizadorparticipante',
                'managed': False,
            },
        ),
    ]
